### PR TITLE
Drop the "type" attribute from feed elements

### PR DESCRIPTION
**Pull request by tdfischer**
Servers are capable of telling clients of the feed type. This is redundant information.

### CODE REVIEW

**Comment by slopjong** [comment]
The field is optional so nobody is forced to use it. @rrix will blame me if I remove it :-D

**Comment by rrix** [comment]
@slopjong No need to be an ass, I'm pretty much done interacting with SpaceAPI things at this point, though not solely because of how you act, so feel free to do what you want with this.

**Comment by rrix** [comment]
Related: Apparently I'm unable to remove myself from the organization, could someone please do me a favor and remove me from the @SpaceApi github org?

**Comment by slopjong** [comment]
@rrix, sorry dude, the question is why you blamed me to not respect the suggestions and comments of the so-called "spaceapi people" while I did. If you followed the changes I made and if you checked the issues/ml again you should have seen, that pretty much everything was discussed somewhere.

In addition these "spaceapi people" always told me that time lacks when I asked to help me working on the spaceapi. So if in over a year almost nobody wants to contribute I welcome your decision.

Since March/April 2013 I walk the do-ocracy way in order to get things done but your behaviour shows me somehow that you don't appreciate this. With the new line I already got more help and feedback than before so it seems I'm on the right track.

<em>Talking</em> about things is simply not enough.

**Pull request closed without merging**
