### PR TITLE
Move open,status,lastchange,icon into a new status group

### PR DESCRIPTION
**Pull request by tdfischer**
This tries to cut down on the number of elements in the root by creating a general-purpose 'status' element.

### CODE REVIEW

**Comment by eastein** [comment]
Pointless and will break people's existing apps. If this didn't already have users, maybe changing this would make sense.

**Comment by slopjong** [comment]
In the future OpenSpaceLint will provide a filter to build a selective directory so that the apps don't break if the specification changes.

The link will look something like directory.json?api[]=0.13&api[]=0.14

**Comment by eastein** [comment]
Missing data is breakage.

**Comment by slopjong** [comment]
If apps rely on a specific version the selective directory prevents breakage. Only the set with those space apis will be delivered (on demand) that are supported by the app.

Consider it as a nice to have feature, no app developer is forced to use it.

**Pull request closed without merging**
